### ISSUE TITLE
Integration and support for sipeed boards

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#122]

**Comment by xijing21** [comment]
除却RISC-V FPGA，其它RISC-V产品参考：https://github.com/ruyisdk/pmd/issues/40

**Comment by KevinMX** [comment]
FPGA 产品已添加：
- TANG Mega 138K Pro

Zephyr 目前无输出，FreeRTOS 和 RT-Thread 可正常启动

**Comment by xen0n** [comment]
done; announced in https://github.com/ruyisdk/packages-index/commit/15330194923aab278262d205a30d87423f708cc7
