### ISSUE TITLE
Integration and support wch boards

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#136]
支持沁恒微电子RISC-V全产品线：https://special.wch.cn/zh_cn/RISCV_MCU_Index/
|   | 产品系列  | MCU      | 开发板型号          | 硬件 |
   | ------------- | --------------------------------------------------------------------------------------------------------------------------------------------- | --------- | ------------------- | ---- |
   | 低功耗蓝牙MCU | 青稞RISC-V蓝牙                                                                                                                                | CH573/1   | CH573F-EVT-C        | 有   |
   |               |                                                                                                                                               | CH583/2/1 | CH582F评估板        | 有   |
   |               |                                                                                                                                               | CH592     | CH592X-EVT-R1       | 有   |
   | 32位通用MCU   | [RISC-V2A](https://shop137880236.taobao.com/category-1748173883.htm?search=y&parentCatId=1748148420&parentCatName=MCU%C0%E0&catName=RISC-V2A#bd) | CH32V003  | CH32V003/203-LinkE  | 有   |
   |               | [RISC-V3A](https://shop137880236.taobao.com/category-1748150549.htm?search=y&parentCatId=1748148420&parentCatName=MCU%C0%E0&catName=RISC-V3A#bd) | CH32V103  | CH32V103C8T6-Link   | 有   |
   |               |                                                                                                                                               | CH32V103  | CH32V103C8T6-EVT-R1 |      |
   |               |                                                                                                                                               | CH32V103  | CH32V103R8T6-EVT-R1 |      |
   |               | [RISC-V4B](https://shop137880236.taobao.com/category-1748150551.htm?search=y&parentCatId=1748148420&parentCatName=MCU%C0%E0&catName=RISC-V4B#bd) | CH32V203  | CH32V203C8T6-EVT-R0 |      |
   |               |                                                                                                                                               | CH32V203  | CH32V203G8R6-EVT-R0 |      |
   |               |                                                                                                                                               | CH32V203  | CH32V203F8P6-EVT-R0 |      |
   |               |                                                                                                                                               | CH32V203  | CH32V203G6U6-EVT-R0 | 有   |
   |               | [RISC-V4C](https://shop137880236.taobao.com/category-1748150552.htm?search=y&parentCatId=1748148420&parentCatName=MCU%C0%E0&catName=RISC-V4C#bd) | CH32V208  | CH32V208WBU6-EVT-R0 | 有   |
   |               | [RISC-V4F](https://shop137880236.taobao.com/category-1748150553.htm?search=y&parentCatId=1748148420&parentCatName=MCU%C0%E0&catName=RISC-V4F#bd) | CH32V307  | CH32V307V-EVT-R2    | 有   |
   |               |                                                                                                                                               | CH32V303  | CH32V303VCT6-EVT-R0 | 有   |
   |               |                                                                                                                                               | CH32V303  | CH32V303CBT6-EVT-R0 |      |
   |               |                                                                                                                                               | CH32V305  | CH32V305FBP6-EVT-R0 | 有   |

**Comment by xen0n** [comment]
https://github.com/ruyisdk/support-matrix/pull/16

然目前有调研结果的 wch 产品均无官方镜像（均为 MCU 评估板，均需自行编译裸机镜像），无法简单集成，考虑 documentation-only 方式支持
