### ISSUE TITLE
XDG_CACHE_HOME 环境变量非空的情形下 progcache 不随该变量变化

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#14]
## RUYI 包管理版本

[20231126](https://mirror.iscas.ac.cn/ruyisdk/ruyi/testing/ruyi.amd64.20231126)

## 问题描述

``XDG_CACHE_HOME`` 环境变量非空的情形下，软件包缓存和本地工具链目录均会跟随该变量的配置，而 ``progcache`` 目录则无视该变量

```bash
$ ls ~/.cache/ruyi/
progcache
$ ls ~/.cache/test/ruyi/
binaries  distfiles  packages-index
$ echo $XDG_CACHE_HOME
/home/hachi/.cache/test
```

**Comment by xen0n** [comment]
Nuitka 未实现此功能，upstream issue TODO
