### ISSUE TITLE
``ruyi list`` 不过滤本机架构不支持的软件包

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#15]
## RUYI 包管理版本

[20231126](https://mirror.iscas.ac.cn/ruyisdk/ruyi/testing/ruyi.amd64.20231126)

## 问题描述

这并不是 bug ，而是请求一个低优先级的特性

部分工具链不支持 riscv64 环境，但是 ``list`` 命令并不会过滤，而是在 install 阶段报错

```
$ pkgname=$(ruyi list | grep -e '^* toolchain' | head -n 1 | cut -d/ -f 2)
$ echo $pkgname
llvm-upstream
$ ruyi install $pkgname
fatal error: package llvm-upstream-17.0.5-ruyi.20231121 declares no binary for 
host riscv64
```

**Comment by xen0n** [comment]
为 `ruyi list` 添加了判断，目前会在某个包不支持当前架构时额外提示 `no binary for current host` 了
