### ISSUE TITLE
ruyi device provision 中 armbian-pine64-star64 镜像上游 url 失效

### ISSUE THREAD

**Issue by delete-cloud** [ruyisdk/ruyi#175]
[package-index](https://github.com/ruyisdk/packages-index) 中 [armbian-pine64-star64](https://github.com/ruyisdk/packages-index/blob/main/manifests/board-image/armbian-pine64-star64/24.8.0-trunk.6.toml) 的 镜像 url 已失效
## 原因：
armbian 仓库 [release](https://github.com/armbian/community/releases) 更新，删除了之前的 tag 导致链接失效，目前有效 url 为 [24.8.0-trunk.314](https://github.com/armbian/community/releases/download/24.8.0-trunk.314/Armbian_community_24.8.0-trunk.314_Star64_noble_edge_5.15.0_minimal.img.xz) 与 [24.8.0-trunk.205](https://github.com/armbian/community/releases/download/24.8.0-trunk.205/Armbian_community_24.8.0-trunk.205_Star64_noble_edge_5.15.0_minimal.img.xz)
## Log:
➜  ~ ruyi device provision

RuyiSDK Device Provisioning Wizard

This is a wizard intended to help you install a system on your device for your
development pleasure, all with ease.

You will be asked some questions that help RuyiSDK understand your device and
your intended configuration, then packages will be downloaded and flashed onto
the device's storage, that you should somehow make available on this host
system beforehand.

Note that, as Ruyi does not run as root, but raw disk access is most likely
required to flash images, you should arrange to allow your user account sudo
access to necessary commands such as dd. Flashing will fail if the sudo
configuration does not allow so.

Continue? (y/N) y

The following devices are currently supported by the wizard. Please pick your device:

  1. Allwinner Nezha D1
  2. Canaan Kendryte K230
  3. Canaan Kendryte K510
  4. Milk-V Duo
  5. Milk-V Duo S
  6. Milk-V Mars
  7. Milk-V Mars CM
  8. Milk-V Meles
  9. Milk-V Pioneer Box
  10. Milk-V Vega
  11. Pine64 Star64
  12. SiFive HiFive Unmatched
  13. Sipeed Lichee Cluster 4A
  14. Sipeed Lichee Console 4A
  15. Sipeed LicheePi 4A
  16. Sipeed Lichee RV
  17. Sipeed LicheeRV Nano
  18. Sipeed Maix-I
  19. Sipeed Tang Mega 138K Pro
  20. StarFive VisionFive
  21. StarFive VisionFive2
  22. WCH CH32V103 EVB
  23. WCH CH32V203 EVB
  24. WCH CH32V208 EVB
  25. WCH CH32V303 EVB
  26. WCH CH32V305 EVB
  27. WCH CH32V307 EVB
  28. WCH CH582F EVB
  29. WCH CH592X EVB

Choice? (1-29) 11

The device has the following variants. Please choose the one corresponding to your hardware at hand:

  1. Pine64 Star64 (generic variant)

Choice? (1-1) 1

The following system configurations are supported by the device variant you have chosen. Please pick the one you want to
put on the device:

  1. Armbian for Pine64 Star64

Choice? (1-1) 1

We are about to download and install the following packages for your device:

 * board-image/armbian-pine64-star64

Proceed? (y/N) y
info: downloading
https://github.com/armbian/community/releases/download/24.8.0-trunk.6/Armbian_community_24.8.0-trunk.6_Star64_noble_edge
_5.15.0_minimal.img.xz to
/home/kina0630/.cache/ruyi/distfiles/Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     12      0 --:--:-- --:--:-- --:--:--    12
warn: file /home/kina0630/.cache/ruyi/distfiles/Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img.xz
is corrupt: wrong sha256 checksum: want bb67aa18093b2f11fdecf217bc49927b56542b0c44f86633fe53f4221a52537d, got
0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5; deleting
fatal error: failed to fetch distfile:
/home/kina0630/.cache/ruyi/distfiles/Armbian_community_24.8.0-trunk.6_Star64_noble_edge_5.15.0_minimal.img.xz failed
integrity checks

Downloads can fail for a multitude of reasons, most of which should not and
cannot be handled by Ruyi. For your convenience though, please check if any
of the following common failure modes apply to you, and take actions
accordingly if one of them turns out to be the case:

* Basic connectivity problems
    - is the gateway reachable?
    - is common websites reachable?
    - is there any DNS pollution?
* Organizational and/or ISP restrictions
    - is there a firewall preventing Ruyi traffic?
    - is your ISP blocking access to the source website?
* Volatile upstream
    - is the recorded link dead? (Please raise a Ruyi issue for a fix!)

**Comment by xen0n** [comment]
Fixed in https://github.com/ruyisdk/packages-index/commit/56297d1417282ca4378e7d0d199dca0d73a257fb.

We are developing a mechanism for automatically tracking upstream releases and bumping versions, so issues like this should become a thing of past after we finish the work. Thanks for filing the issue.
