### ISSUE TITLE
ruyi news 功能换行缺字

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#181]
## ruyi 版本

[0.15.0](https://github.com/ruyisdk/ruyi/releases/tag/0.15.0)

## 问题描述

当终端宽度无法显示一行内容时， ruyi 会进行换行，但是换行有缺字的情况，在各个平台均可复现。

![截图 2024-07-26 11-03-33](https://github.com/user-attachments/assets/cf7ec5c2-14e1-443b-b997-afadf79288bc)

图中可以看到 amd64.tar.zst 被截断，并且 ``4.`` 两个字符缺失。

**Comment by xen0n** [comment]
related: https://github.com/Textualize/rich/issues/3154

We may have to disable word wrapping for our Markdown (or even the entire CLI) output as a whole.
