### ISSUE TITLE
wps-office 上游新版本 12.1.0.17885

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#183]
## ruyi 版本

[0.15.0](https://github.com/ruyisdk/ruyi/releases/tag/0.15.0)

## 问题描述

[WPS 官网](https://linux.wps.cn/)已经更新版本到 11.1.0.11723，且只给出了 x86_64 架构的下载链接。

**Comment by xen0n** [comment]
Should be fixed in https://github.com/ruyisdk/packages-index/commit/d7b7b09dfc08614330c59c52450cb20ff416f0db.

**Comment by weilinfox** [comment]
## ruyi 版本

[0.18.0](https://github.com/ruyisdk/ruyi/releases/tag/0.18.0)

## 问题描述

[WPS 官网](https://linux.wps.cn/)已经更新版本到 12.1.0.17885 2024.09.12

**Comment by xen0n** [comment]
done in https://github.com/ruyisdk/packages-index/commit/0b4bfbaa8e7662371437b0c1a5529c2ff9698d76
