### ISSUE TITLE
``ruyi install slug:llvm-upstream-20231121`` 找不到软件包

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#19]
### RUYI 包管理版本

[20231204](https://mirror.iscas.ac.cn/ruyisdk/ruyi/testing/ruyi.amd64.20231204)

### 问题描述

安装 llvm-upstream 无法指定 slug 安装：

```bash
ruyi install slug:llvm-upstream-20231121
fatal error: atom slug:llvm-upstream-20231121 matches no package in the repository
```

直接使用包名安装正常。

**Comment by xen0n** [comment]
预期的：slug 的设计是最早没有完善的 repo、包版本匹配机制时，为了仍然能方便定位到唯一包，而投机取巧的产物。后续 slug 只会用于为超常用的软件包特定版本提供短名称，其他包默认都不会有 slug。
