### ISSUE TITLE
ruyi 的 python-frontmatter 依赖问题

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#191]
## 问题描述

发行版广泛没有打包 [python-frontmatter](https://github.com/eyeseast/python-frontmatter)

这个项目本身很小，可能可以考虑替代方案？

**Comment by xen0n** [comment]
经检查，这个项目不只支持 YAML frontmatter，还默认自带了 JSON 和 TOML 的 frontmatter 支持，而我们没有预期会用到这部分。

为了减少 surprises，直接去掉依赖最简单，只实现必要的部分即可。#193
