### ISSUE TITLE
add gcc and examples  for milkv duo 

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#194]
milkv duo 集成新需求：
https://github.com/ruyisdk/pmd/issues/82#issuecomment-2342466421

1. 编译工具链 [riscv64-linux-musl-x86_64](https://github.com/milkv-duo/host-tools/tree/master/gcc/riscv64-linux-musl-x86_64) （暂时只找到二进制），ruyisdk考虑可以通过二次分发方式集成到包管理器。
2. wiringx 示例代码 [duo-examples](https://github.com/milkv-duo/duo-examples) 集成到包管理器。

**Comment by xen0n** [comment]
`milkv-duo/examples` packaged: https://github.com/ruyisdk/packages-index/commit/6a8b17d4614f5443e463734e138f6c03ae12e3ec

**Comment by xen0n** [comment]
https://github.com/milkv-duo/host-tools snapshots re-packaged: https://github.com/ruyisdk/packages-index/commit/f0148e930da8a34ce4ce26ea5e2e1158e5598f2c
