### ISSUE TITLE
修改milkv duo镜像默认的系统登录用户名和密码

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#196]
为了解决目前诸如milkv duo 官方sdk生成的镜像默认系统登录用户是root，密码是milkv，其它开发板或者系统又是其它自定义的用户名和密码；而且在启动时没有提示用户名密码，用户不知道如何登录，必须通过文档去寻找的问题。

目前通过“镜像后处理方式”（镜像安装成功后，通过脚本等其它手段修改系统内的配置信息，达到修改和更新默认用户和密码的目的）修改milkv duo 系统默认登录用户为：ruyisdk   密码为：ruyisdk

**Comment by xen0n** [comment]
增加了简单的镜像重打包工具 https://github.com/ruyisdk/ruyici/blob/main/repack-board-image.sh

用这个脚本可以重新打包常见的设备系统镜像：

* 不采用只读文件系统实现 root 分区的，
* 不采用复杂 fstab 的。

自动加入 `ruyisdk` 用户，密码为 `ruyisdk`，UID = GID = 11111。因为 UID 1000 不一定是个好选择（厂商如果给一个默认的非 root 用户就很可能占用了它），所以随便选了一个数。

有其他建议的 UID/GID 可以提，范围应该是 1000~6553x，65535 是 nobody，65534 等等的不确定

**Comment by xen0n** [comment]
done for new `milkv-duo*` images since https://github.com/ruyisdk/packages-index/commit/9aec22b7ee552e317c372948c12b68fdd76b1e6b
