### ISSUE TITLE
增加ruyi reset功能重置用户配置文件

### ISSUE THREAD

**Issue by ArielHeleneto** [ruyisdk/ruyi#200]
增加ruyi reset功能重置用户配置文件

增加ruyi unisntall 变量

增加 ruyi remove 用于移除所有用户配置文件

**Comment by xen0n** [comment]
卸载功能已经有了：`ruyi self uninstall`

在 #206 加了个 `ruyi self clean` 可以自行排列组合要删的内容，看下够不够用？
