### ISSUE TITLE
xthead 工具链构建产物无法在 RevyOS 运行

### ISSUE THREAD

**Issue by xen0n** [ruyisdk/ruyi#22]
split from #21

原因大概是 T-Head 工具链使用了不规范的 ELF interpreter 路径，这在 RevyOS 上应该不存在：

```
$ file xx 
xx: ELF 64-bit LSB executable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-riscv64xthead-lp64d.so.1, BuildID[sha1]=ecead183d362b63010ce986ecc1c1fe2fa3ba703, for GNU/Linux 4.15.0, with debug_info, not stripped
```

注意 `/lib/ld-linux-riscv64xthead-lp64d.so.1` 这个文件名里有私货。

**Comment by xen0n** [comment]
可能是因为最初做 xthead 工具链的时候，出于某些原因（目前忘记了）故意跳过了 xthead glibc 的[这个提交](https://github.com/T-head-Semi/glibc/commit/7f000564c1280a8a93debbb25dfe9784429ac10c)，导致生成的 sysroot 的 multilib 布局与常规 riscv64 lp64d 系统不同。

目前正在重新加入这个提交构建 xthead 工具链，以测试。

**Comment by RevySR** [comment]
> 可能是因为最初做 xthead 工具链的时候，出于某些原因（目前忘记了）故意跳过了 xthead glibc 的[这个提交](https://github.com/T-head-Semi/glibc/commit/7f000564c1280a8a93debbb25dfe9784429ac10c)，导致生成的 sysroot 的 multilib 布局与常规 riscv64 lp64d 系统不同。
> 
> 目前正在重新加入这个提交构建 xthead 工具链，以测试。

并不是跳过这个提交 这个提交在v2.6.1工具链之后发布的 可以支持的只有v2.6.2/v2.8.0 这两个版本源码都暂时没有公布完成



> 原先做的工具链没问题，@RevySR 的回复：
> 
> * 也可搭配平头哥出品的 2.8.0 工具链使用（但此版本工具链外部可复现源码尚未公开）
> * 带 xthead 字样的平头哥特色 multilib 配置，已经在 RevyOS 最新版得到支持，后续等 RevyOS 发新版即可
> 
> 等确认解决了之后再 close 此 issue

原先做的工具链就是有问题的工具链 这个是在revyos这边要求下进行回滚

revyos原来不计划有任何交叉工具链 之前维护了一个版本也和thead工具链版本选型不同
工具链：gcc v10.4.0 / binutils 2.40 / glibc 2.36
https://github.com/revyos/revyos-gnu-toolchain/tree/thead-toolchains

当前版本还没有完整全部更新到revyos仓库里

**Comment by RevySR** [comment]
> 可能是因为最初做 xthead 工具链的时候，出于某些原因（目前忘记了）故意跳过了 xthead glibc 的[这个提交](https://github.com/T-head-Semi/glibc/commit/7f000564c1280a8a93debbb25dfe9784429ac10c)，导致生成的 sysroot 的 multilib 布局与常规 riscv64 lp64d 系统不同。
> 
> 目前正在重新加入这个提交构建 xthead 工具链，以测试。

multilib布局问题是为了兼容rv32/rv64各种玄铁组合 revyos无此需求 所以没有做支持

**Comment by xen0n** [comment]
> 可以支持的只有v2.6.2/v2.8.0 这两个版本源码都暂时没有公布完成

Marking as blocked due to this fact.

**Comment by RevySR** [comment]
https://github.com/T-head-Semi/xuantie-gnu-toolchain/commits/xuantie-gnu-toolchain/

v2.8.0已同步更新

**Comment by xen0n** [comment]
Triage: 截至 2024.01: 需要重新打包 xthead 工具链，并重新评估此 issue。

**Comment by xijing21** [comment]
在RISC-V笔记本电脑上复现了这个问题：https://github.com/ruyisdk/pmd/blob/main/RVBoards/rvBook/ruyi-install.md
建议将 xthead 工具链重新打包工作加入到v0.5版本。

**Comment by xen0n** [comment]
Fixed with ruyisdk/ruyici#5 (building packages right now):

```c
// x.c
#include <stdio.h>

int main()
{
        printf("hello thead\n");
        return 0;
}
```

```
$ ./RuyiSDK-20240222-T-Head-Sources-T-Head-2.8.0-riscv64-plctxthead-linux-gnu/bin/riscv64-plctxthead-linux-gnu-gcc -O2 -o x x.c
$ QEMU_CPU=c910v QEMU_LD_PREFIX=/usr/riscv64-unknown-linux-gnu /home/xenon/.local/share/ruyi/binaries/x86_64/qemu-user-riscv-xthead-6.1.0-ruyi.20231207+g03813c9fe8/bin/qemu-riscv64 ./x
hello thead
```

**Comment by xen0n** [comment]
```
ruyi update
ruyi install gnu-plct-xthead  # 2.8.0 版本
# 自行 rm -rf 旧版
```
