### ISSUE TITLE
wps 官网更新到了 17900

### ISSUE THREAD

**Issue by wzzc-dev** [ruyisdk/ruyi#243]
现在安装的时候报错 

[test@openEuler distfiles]$ ruyi install --host x86_64 wps-office
fatal error: the file 
'/home/test/.cache/ruyi/distfiles/wps-office_12.1.0.17885_amd64.deb' cannot be 
automatically fetched
info: instructions on fetching this file:
info: 您需要从 WPS Office 下载页面手工下载该软件包：

* 访问 https://linux.wps.cn
* 单击“立即下载”
* 确保“64位 Deb格式”一列下显示的软件版本号为 12.1.0.17885
* 单击该列中的“For X64”以开始下载

将下载完成的文件置于 /home/test/.cache/ruyi/distfiles/wps-office_12.1.0.17885_amd64.deb 
并重新执行安装命令。

**Comment by stydxm** [comment]
seems file `https://mirror.iscas.ac.cn/ruyisdk/dist/wps-office_12.1.0.17885_amd64.deb` missing

https://github.com/ruyisdk/packages-index/blob/5d44a0d3d2395a8f772d185da8db4aae59422bf1/manifests/extra/wps-office/12.1.0-r.17885.toml#L8

**Comment by weilinfox** [comment]
> 现在安装的时候报错
> 
> [test@openEuler distfiles]$ ruyi install --host x86_64 wps-office fatal error: the file '/home/test/.cache/ruyi/distfiles/wps-office_12.1.0.17885_amd64.deb' cannot be automatically fetched info: instructions on fetching this file: info: 您需要从 WPS Office 下载页面手工下载该软件包：
> 
>     * 访问 https://linux.wps.cn
> 
>     * 单击“立即下载”
> 
>     * 确保“64位 Deb格式”一列下显示的软件版本号为 12.1.0.17885
> 
>     * 单击该列中的“For X64”以开始下载
> 
> 
> 将下载完成的文件置于 /home/test/.cache/ruyi/distfiles/wps-office_12.1.0.17885_amd64.deb 并重新执行安装命令。

这是正常的，考虑到再分发的问题。如果不希望开浏览器的话可以考虑文档中的参考方案 [WPS Office 版本下载参考](https://ruyisdk.org/docs/changelog/0.14.0/#wps-office-%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD%E5%8F%82%E8%80%83)，或者参考 aur/wps-office-cn 的 [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wps-office-cn&id=da5958b5179c1345d24840ea30803a8d52c8d0c6#n21)。
