### ISSUE TITLE
2024.06 milestone planning

### ISSUE THREAD

**Issue by xen0n** [ruyisdk/ruyi#28]
See: https://github.com/xijing21/ruyi-pmd/blob/main/docs/process/plan/24.06.md

**Comment by xijing21** [comment]
已经迁移到 https://github.com/ruyisdk/pmd/blob/main/plan/24.06.md
包管理器部分还请继续补充下

**Comment by xen0n** [comment]
Long-term planning is now mostly happening in the pmd repo, closing this as being superseded.
