### ISSUE TITLE
RISC-V 开发板系统镜像安装工具，增加4款RISC-V开发板

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#41]
扩展4款支持的开发板（全dd模式）：矽速 Lichee RV 、 全志哪吒 D1、VisionFive 1 & 2；

**Comment by KevinMX** [comment]
D1 / Lichee RV & Nezha:
- 镜像（openEuler 23.03，两款开发板共用）: https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.03-V1-riscv64/D1/
- 文档：https://gitee.com/openeuler/RISC-V/blob/master/release/openEuler-23.03/Installation_Book/D1_and_Licheerv/README.md

VisionFive: 
- 镜像（openEuler 23.09 Preview）: https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/Visionfive/
- 文档：https://gitee.com/openeuler/RISC-V/blob/master/release/openEuler-23.03/Installation_Book/Visionfive/README.md

VisionFive 2:
- 镜像（openEuler 23.09 Preview）：https://mirror.iscas.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/preview/openEuler-23.09-V1-riscv64/Visionfive2/
- 文档：https://gitee.com/openeuler/RISC-V/blob/master/release/openEuler-23.03/Installation_Book/Visionfive2/README.md

**Comment by xen0n** [comment]
Proposed device model slugs:

* `sipeed-licheerv`: Sipeed didn't have an official abbreviation according to [the wiki page](https://wiki.sipeed.com/hardware/zh/lichee/RV/RV.html) (see the page URL; in contrast, LicheePi 4A is *officially* abbreviated as `lpi4a`).
* `awol-d1dev`: official product page is https://d1.docs.aw-ol.com/d1_dev/ (certificate is expired though), hence `awol` and `d1` ("Nezha" seems only a brand name that's not part of the codename)
* `starfive-visionfive`: officially called so: https://github.com/starfive-tech/VisionFive
* `starfive-visionfive2`: officially called so: https://github.com/starfive-tech/VisionFive2

Is that okay?

**Comment by xen0n** [comment]
And -- is "Lichee RV" actually compatible enough to "Nezha D1" so that they'd be better represented as one model?

**Comment by KevinMX** [comment]
> And -- is "Lichee RV" actually compatible enough with "Nezha D1" so that they'd be better represented as one model?

In openEuler RISC-V 23.03 they shares the same system image, but different DTBs. Although even with Nezha D1's DTB selected, Lichee RV can still boot & operate without any issues. I think this is fine.

As in the bootloader / GRUB config of the image says:

```
menuentry 'openEuler riscv64 6.1.0 Nezha' {
    linux /vmlinuz-openEuler rw earlyprintk=sunxi-uart,0x02500000 console=ttyS0,115200 console=tty0 loglevel=8  root=/dev/mmcblk0p4 selinux=0 rhgb LANG=en_US.UTF-8
    devicetree /dtbs/allwinner/sun20i-d1-nezha.dtb
}

menuentry 'openEuler riscv64 6.1.0 Lichee RV Dock' {
    linux /vmlinuz-openEuler rw earlyprintk=sunxi-uart,0x02500000 console=ttyS0,115200 console=tty0 loglevel=8  root=/dev/mmcblk0p4 selinux=0 rhgb LANG=en_US.UTF-8
    devicetree /dtbs/allwinner/sun20i-d1-lichee-rv-dock.dtb
}
```

**Comment by KevinMX** [comment]
> And -- is "Lichee RV" actually compatible enough with "Nezha D1" so that they'd be better represented as one model?

Booting as default (use AllWinner Nezha's dtb) on Lichee RV Dock:

```log
[root@openeuler-riscv64 ~]# dmesg -Hw | grep eth
[  +0.008527] dwmac-sun8i 4500000.ethernet: IRQ eth_wake_irq not found
[  +0.006463] dwmac-sun8i 4500000.ethernet: IRQ eth_lpi not found
[  +0.006425] dwmac-sun8i 4500000.ethernet: PTP uses main clock
[  +0.005866] dwmac-sun8i 4500000.ethernet: Current syscon value is not the default 50006 (expect 0)
[  +0.009288] dwmac-sun8i 4500000.ethernet: No HW DMA feature register supported
[  +0.007334] dwmac-sun8i 4500000.ethernet: RX Checksum Offload Engine supported
[  +0.007297] dwmac-sun8i 4500000.ethernet: COE Type 2
[  +0.005026] dwmac-sun8i 4500000.ethernet: TX Checksum insertion supported
[  +0.006840] dwmac-sun8i 4500000.ethernet: Normal descriptors
[  +0.005708] dwmac-sun8i 4500000.ethernet: Chain mode enabled
[  +0.005725] dwmac-sun8i 4500000.ethernet: device MAC address 36:f7:d5:69:49:4b
[  +0.110815] dwmac-sun8i 4500000.ethernet: EMAC reset timeout
[  +0.005740] dwmac-sun8i 4500000.ethernet eth0: stmmac_dvr_remove: removing driver
[  +0.018064] dwmac-sun8i: probe of 4500000.ethernet failed with error -110
```

There's no ethernet PHY present so it will fail, but other features will work just fine (e.g. WiFi, BT, USB, HDMI video out).
While it does work, there will be some differences. Users should change their GRUB defaults.

**Comment by xen0n** [comment]
> they share the same system image, but different DTBs

So from a user's perspective, they are different models if the user wishes to make use of all features provided by the hardware, although a lot of code is shared.

**Comment by xen0n** [comment]
Board images added as of https://github.com/ruyisdk/packages-index/commit/aef81619f5d78092db1912ff05b44a891bb67d8d.
