### ISSUE TITLE
将DynamoRIO 集成到包管理器中，使用户能够通过ruyi下载安装

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#50]

**Comment by xen0n** [comment]
@xijing21: 需要提供 amd64/arm64/riscv64 三种架构的包吗？

cc @ksco: 可以提供以下信息：

* 如果由上游或者你来出二进制包，那么可以给出这些包的下载地址的权威上游
* 如果由 ruyi 来从源码构建，那么可以给一下推荐的上游 Git repo、tag 信息，以及推荐的 build instructions
* 总之也可以记录一下预期的安装之后的目录布局 & 用户使用方式

**Comment by ksco** [comment]
嗨，相关信息如下：

**官网**：https://dynamorio.org/

**Git repo**：https://github.com/DynamoRIO/dynamorio master

**RISC-V port 目前状态**：初步的试验性支持，上游不提供 RISC-V 的 release，目前只能从源码构建。

**自行构建与安装**：

RISC-V Linux 原生的构建和安装可以完全参照官方文档：https://dynamorio.org/page_building.html

交叉编译可以参考 “Cross-Compiling for 64-bit ARM (AArch64) on Linux” 一节的内容，但 `CMAKE_TOOLCHAIN_FILE` 需要改为 `../make/toolchain-riscv64.cmake`。

“Configuring Your Build” 一节中列出了常用的构建选项，建议打开 `BUILD_TOOLS`、`BUILD_SAMPLES` 和 `BUILD_TESTS`。

编译成功后，运行 `make install` 可以将 DynamoRIO 安装到配置好的 `INSTALL_PREFIX` 中，目录结构如下：

```
.
├── ACKNOWLEDGEMENTS
├── License.txt
├── README
├── bin64
├── cmake
├── docs
├── docs_embed
├── ext
├── include
├── lib64
├── logs
├── samples
└── tools
```

**预期使用方式**：

`bin64` 中提供了 一系列可执行文件，最常用的是 `bin64/drrun`。例如使用 `drrun <program>` 就可以在 DR 中运行任意 Linux 程序（当然目前 RISC-V port 并不是所有程序都可以运行）。

`samples` 中是一些 API 使用的演示样例，例如可以使用如下命令计算运行 `echo` 命令需要执行的指令数量：

```bash
bin64/drrun -c samples/bin64/libinscount_test.so -- echo
```

`tools` 中是官方维护的一些客户端，例如可以使用如下命令模拟计算运行 `echo` 命令缓存访问的重用距离：

```
bin64/drrun -t drcachesim -simulator_type reuse_distance -- echo
```

（`-c` 和 `-t` 参数都是 DynamoRIO 中挂载客户端的方式）

DynamoRIO 提供了一整套 API 供开发者根据需求开发自己的客户端，然后挂载到 `drrun` 下使用。

`include` 和 `lib64` 目录中提供了基础的依赖头文件和共享库，`ext` 中则包括了官方基于基础 API 开发的诸多扩展 API 的相关依赖文件。

**测试**：

构建完成后，可以使用 `ctest -L RUNS_ON_QEMU` 来运行目前已在 RISC-V QEMU 上开启的测试。原生也可以跑，但有一个测试用例 `code_api|api.ir` 会失败，这个是预期的。

**Comment by xijing21** [comment]
> @xijing21: 需要提供 amd64/arm64/riscv64 三种架构的包吗？
是的，DynamoRIO 用于软件测试、性能优化、调试、安全分析、内存检查等，最终需要提供三种架构的包，优先考虑提供riscv64

**Comment by xen0n** [comment]
由于[上游限制](https://github.com/DynamoRIO/dynamorio/issues/1684)，无法在 amd64 与 arm64 平台上打出 targeting riscv64 的 DynamoRIO 二进制包，因此在上游解决此限制之前，只能为 riscv64 平台提供二进制包。

**Comment by xen0n** [comment]
`ruyi install analyzer/dynamorio-riscv`

**Comment by ksco** [comment]
> 由于[上游限制](https://github.com/DynamoRIO/dynamorio/issues/1684)，无法在 amd64 与 arm64 平台上打出 targeting riscv64 的 DynamoRIO 二进制包，因此在上游解决此限制之前，只能为 riscv64 平台提供二进制包。

这个不太可能会解决，DynamoRIO 本质是个同架构的二进制翻译工具。

**Comment by xijing21** [comment]
在riscv笔记本上尝试了下DynamoRIO 得安装，情况如下：
![image](https://github.com/ruyisdk/ruyi/assets/84754181/57e4254a-7139-4e16-b75e-72369876c742)
![image](https://github.com/ruyisdk/ruyi/assets/84754181/9dd5ca32-f218-47b3-a720-3c036b884f19)
![image](https://github.com/ruyisdk/ruyi/assets/84754181/a3708ac2-bdf2-4916-a73c-bfdca88ea5a0)
