### ISSUE TITLE
fix ruyisdk/pmd#13 : 支持香山标准指令集

### ISSUE THREAD

**Issue by ArielHeleneto** [ruyisdk/ruyi#55]
目前已知香山处理器南湖架构支持 RV64GCBK 扩展（具体指令集字符串为 `RV64IMAFDC_zba_zbb_zbc_zbs_zbkb_zbkc_zbkx_zknd_zkne_zknh_zksed_zksh_svinval`）。

香山版本的工具链见 [OpenXiangShan/riscv-gnu-toolchain](https://github.com/OpenXiangShan/riscv-gnu-toolchain)

目前的编译方案和 [riscv-gnu-toolchain官方文档](https://github.com/riscv-collab/riscv-gnu-toolchain#prerequisites) 或参考 [在国内网络环境下编译 riscv-gnu-toolchain](https://github.com/ArielHeleneto/Work-PLCT/blob/master/help/build-riscv-toolchain.md)

一份充满历史气息的香山提供的 [GCB 工具链使用说明](https://xiangshan-doc.readthedocs.io/zh-cn/latest/compiler/gnu_toolchain/#_2)

**Comment by xen0n** [comment]
如果这里提到的所有扩展都已被 GCC 主线支持，那么就只需添加一个 profile 即可支持 target 香山。否则可能需要集成一些补丁并制作相应的工具链包。

**Comment by ArielHeleneto** [comment]
> 如果这里提到的所有扩展都已被 GCC 主线支持，那么就只需添加一个 profile 即可支持 target 香山。否则可能需要集成一些补丁并制作相应的工具链包。

submodule 版本似乎不够高以至于不支持B扩展
