### ISSUE TITLE
集成 K230（K230 Board）和 U740（unmatched）到ruyisdk安装器

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#65]

**Comment by xen0n** [comment]
@xijing21 请提供拟支持的硬件 - OS 组合（最好有镜像），以便打包，感谢！

**Comment by xijing21** [comment]
@YunxiangLuo 请罗老师支持相关镜像链接

**Comment by xijing21** [comment]
k230镜像：https://gitlab.inuyasha.love/weilinfox/plct-working/-/blob/master/Done/Month08/Week3/CanMV-K230.md

YunxiangLuo 对K230的镜像进行的验证：
1. debian镜像：https://kendryte-download.canaan-creative.com/developer/k230/canmv_debian_sdcard_sdk_1.3.img.gz
![404632bb8c00d9df30b80ee181a52077_](https://github.com/ruyisdk/ruyi/assets/84754181/e70b913c-a41c-4e75-8f12-88e9d514e434)

2. ubuntu镜像：https://kendryte-download.canaan-creative.com/developer/k230/canmv_ubuntu_sdcard_1.3.img.gz
![bc81e8db80375eb1ca201837be08fda3_](https://github.com/ruyisdk/ruyi/assets/84754181/01476a2a-c4cf-40a8-811f-650bf5113534)

![23d51b760878ae025c50152df8def80f_](https://github.com/ruyisdk/ruyi/assets/84754181/a58a314f-3172-4138-8e2e-ff0dbce8adc5)

**Comment by KevinMX** [comment]
Zephyr on Unmatched: https://github.com/KevinMX/PLCT-Tarsier-Works/blob/main/misc/month10/Zephyr_Unmatched.md

非 dd 镜像，目前看来集成可能会有问题？

（其他镜像后续补充）

**Comment by Pagerd** [comment]
HiFive Unmatched:

1.OpenWrt 安装文档 [文档](https://github.com/Pagerd/PLCT/blob/main/Report/week/week33/OpenWrt.md)
系统镜像：https://firmware-selector.openwrt.org/?version=23.05.2&target=sifiveu%2Fgeneric&id=sifive_unmatched
经验证dd到SD卡后可以在Unmatched上启动
![2](https://github.com/ruyisdk/ruyi/assets/60070497/ae160768-6f44-456b-9fec-4ece2c26cb06)

**Comment by xen0n** [comment]
K230 + CanMV Debian SDK done at https://github.com/ruyisdk/packages-index/commit/a6dd97124774935c929b2555547d4419e23a7e43

**Comment by xen0n** [comment]
K230 + CanMV Ubuntu SDK done at https://github.com/ruyisdk/packages-index/commit/0da51c35f5ebf3268521109a6a0235855af3953b

**Comment by xen0n** [comment]
Unmatched + openEuler done at https://github.com/ruyisdk/packages-index/commit/38363a9afa346a606e21254ba9dc87c7348f1bfc

**Comment by KevinMX** [comment]
Confirms FreeBSD is working.
Ref: [unmatch-freeBSD.md](https://github.com/KotorinMinami/plct-working/blob/main/RUYI/borad/unmatch-freeBSD.md)
Flashed these 2 images on Windows via Rufus.
Requires:
- 1 microSD card / onboard SPI NOR Flash w/U-Boot + 1 USB Drive / 1 M.2 NVMe SSD

I used: 1* SanDisk Extreme Pro 64G + Freedom U SDK image + 1* M.2 NVMe SSD (Intel Optane 16G, MEMPEK1W016GA)
Steps:
- Use the microSD card which comes with the board
  - Or manually flash the latest Freedom-U-SDK image from [SiFive](https://github.com/sifive/freedom-u-sdk/releases/latest), e.g. [demo-coreip-cli-unmatched.rootfs.wic.xz](https://github.com/sifive/freedom-u-sdk/releases/download/2024.01.00/demo-coreip-cli-unmatched.rootfs.wic.xz) (*I choosed this one*)
  - Or manually flash U-Boot (unverified)
- Flash FreeBSD image to USB Drive or SSD
  - Image: [FreeBSD.org](https://download.freebsd.org/releases/riscv/riscv64/ISO-IMAGES/14.0/FreeBSD-14.0-RELEASE-riscv-riscv64-mini-memstick.img.xz) | [USTC mirror](https://mirrors.ustc.edu.cn/freebsd/releases/riscv/riscv64/ISO-IMAGES/14.0/FreeBSD-14.0-RELEASE-riscv-riscv64-mini-memstick.img.xz)
- Proceeds to LiveCD or install.

<details>
  <summary>Screenshots</summary>
![image](https://github.com/ruyisdk/ruyi/assets/17025286/1f709fe0-d233-4107-8edc-8c4fb6a23216)
![image](https://github.com/ruyisdk/ruyi/assets/17025286/a5a39f97-949e-4ef1-bed1-a805485900f0)
</details>
