### ISSUE TITLE
支持在 CI 环境构建 ruyi 二进制

### ISSUE THREAD

**Issue by ArielHeleneto** [ruyisdk/ruyi#7]
构建 构建CI

**Comment by weilinfox** [comment]
Jenkins CI 已经跑通，有需要可以接入

https://jenkins.inuyasha.love/job/ruyi-auto-build/53/

https://jenkins.inuyasha.love/job/ruyi-auto-build/56/

**Comment by weilinfox** [comment]
这边设定成每日构建了，每天凌晨 3:36 CST 会自动构建一次
https://jenkins.inuyasha.love/job/ruyi-auto-build/

**Comment by xen0n** [comment]
现在已经有完整的 GitHub Actions 支持了，后续将进一步把 release automation 也做了

本 issue 关心的是在 CI 中构建，已经实现了，因此先把 issue 关掉了 ;-)
