### ISSUE TITLE
将新增验证的unmatched可用操作系统增加集成到安装器中

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#77]
目前新增验证的unmatched可用操作系统有：ubuntu、openlylin、openbsd、freebsd、Openwrt

请 @YunxiangLuo @KevinMX 等老师提供验证可用的镜像链接和相关文档

**Comment by Pagerd** [comment]
OpenWrt 
安装方法：直接将镜像dd到SD卡启动即可
文档 [文档](https://github.com/Pagerd/PLCT/blob/main/Report/week/week33/OpenWrt.md)
系统镜像：https://firmware-selector.openwrt.org/?version=23.05.2&target=sifiveu%2Fgeneric&id=sifive_unmatched

**Comment by KevinMX** [comment]
https://github.com/ruyisdk/ruyi/issues/65
- Ubuntu: 直接 dd 进 microSD 卡；系统镜像 [官方](https://ubuntu.com/download/risc-v) | [(TUNA)](https://mirror.tuna.tsinghua.edu.cn/ubuntu-cdimage/releases/mantic/release/ubuntu-23.10-preinstalled-server-riscv64+unmatched.img.xz)
- OpenKylin (v1.0): 直接 dd 进 microSD 卡；[系统镜像](https://www.openkylin.top/downloads/download-smp.php?id=20)
- OpenBSD/FreeBSD: 见 https://github.com/ruyisdk/ruyi/issues/65#issuecomment-1970489466
  - 需要原装 microSD 卡，或将 U-Boot/Freedom U SDK dd 进 microSD 卡
  - 将安装镜像 dd 进 U 盘
  - 可从 U 盘启动 LiveCD 或者安装程序

**Comment by xijing21** [comment]
![image](https://github.com/ruyisdk/ruyi/assets/84754181/1fb6d042-8cc9-4cd8-afec-aef20e3e4f81)

新增支持操作系统需求似乎还未能体现

**Comment by xijing21** [comment]
ubuntu、openlylin、openbsd、freebsd 这4个操作系统目前还有什么问题么？还未能在列表中显示

**Comment by xen0n** [comment]
> ubuntu、openlylin、openbsd、freebsd 这4个操作系统目前还有什么问题么？还未能在列表中显示

Ubuntu、openKylin 已处理（openKylin 官网的动态下载链接指向的 163 镜像源，十分之慢，换了源才有速度）

https://github.com/ruyisdk/ruyi/issues/77#issuecomment-1972860704 提到的 OpenBSD、FreeBSD 镜像，实则为安装介质镜像。目前 Ruyi 设备安装器适合承担帮用户做启动盘的需求吗？

**Comment by KevinMX** [comment]
> Ubuntu、openKylin 已处理（openKylin 官网的动态下载链接指向的 163 镜像源，十分之慢，换了源才有速度）

openKylin 官网似乎是根据访客 IP 随机/动态 `302 Redirect`，我这边会指向阿里云（较慢）或者其他高校源（较快）。

**Comment by xijing21** [comment]
https://github.com/ruyisdk/ruyi/issues/77#issuecomment-1972860704 提到的 OpenBSD、FreeBSD 镜像，实则为安装介质镜像。目前 Ruyi 设备安装器适合承担帮用户做启动盘的需求吗？
关于这一点，经与需求方确认，涉及到用户需要下载文件的，建议提供将OpenBSD、FreeBSD 镜像 dd 到 U盘等介质，提供安装介质镜像，并给予用户相应提示；

**Comment by xen0n** [comment]
FreeBSD and OpenBSD done in https://github.com/ruyisdk/packages-index/commit/53347bb7058109abb7c51b9f2ea9c2ca7ab3a49e

closing
