### ISSUE TITLE
系统安装器：增加对Duo S、Mars、Vega 3个产品的支持

### ISSUE THREAD

**Issue by xijing21** [ruyisdk/ruyi#92]
由 @YunxiangLuo  测试小队提供验证的镜像文件地址

**Comment by KevinMX** [comment]
Milk-V Duo S: https://github.com/ruyisdk/support-matrix/tree/main/Duo_S
Milk-V Mars: https://github.com/ruyisdk/support-matrix/tree/main/Mars
Milk-V Vega: https://github.com/ruyisdk/support-matrix/tree/main/Vega

**Comment by xen0n** [comment]
Duo S、Mars、Mars CM 完成

Vega：没有可用镜像

**Comment by xen0n** [comment]
关于 Vega 支持：#109

本 issue 剩余部分都完成了，先关掉
